services:
  dbserver:
    image: mysql:9.2
    container_name: priceComparatorDB
    environment:
      MYSQL_ROOT_PASSWORD: dicp
      MYSQL_DATABASE: priceComparator_ant
      MYSQL_USER: bob
      MYSQL_PASSWORD: hardtime
    volumes:
      # le dossier /docker-entrypoint-initdb.d est un dossier spécial
      # MySQL va automatiquement exécuter tous les scripts qui s'y trouvent au démarrage
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

  # ATTENTION les noms de services ne doivent pas contenir de majuscule
  apiserver:
    build: ./api
    container_name: apiserver
    depends_on:
      - dbserver
    ports:
      - "3000:3000"

  web:
    image: nginx:alpine-slim
    container_name: webProxy
    depends_on:
      - apiserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./website:/usr/share/nginx/html
    ports:
      - "8080:8080"
